apiVersion: v1
kind: BuildConfig
metadata:
  name: jenkins-test
  labels:
    name: jenkins-test
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "myapp", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
    -
    -
  runPolicy: Serial
  source:
    type: None
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
          pipeline {
            agent {
              label 'maven'
            }
            stages {
              stage('Build App') {
                steps {
                  git branch: 'master', url: 'https://github.com/daniyalj/create-objects-jenkins.git'
                  sh 'oc whoami'
                  sh 'oc project'
                }
              }
            }
          }
  output:
  resources:
  postCommit:
