apiVersion: v1
kind: Service
metadata:
  name: testsvc      
spec:
  selector:                  
    docker-registry: default
  ports:
  - nodePort: 0
    port: 5000               
    protocol: TCP
    targetPort: 5000
